#define BOOTLOADER_START_ADDRESS 0x08000000
#define BOOTLOADER_SIZE 0x5000
#define APPLICATION_START_ADDRESS (BOOTLOADER_START_ADDRESS + BOOTLOADER_SIZE)
#define APPLICATION_SIZE 0xB000
#define RESET_HANDLER_ADDRESS (APPLICATION_START_ADDRESS + 0x04)

#define RAM_START_ADDRESS 0x20000000
#define RAM_SIZE 0x5000
#define RAM_END_ADDRESS (RAM_START_ADDRESS + RAM_SIZE - 1)
